[package]
name = "ipc-com"
version = "0.0.9"
edition = "2024"
description = "Simple shared-memory IPC for Rust"
license = "Apache-2.0"
repository = "https://github.com/CosmicalBit/Ipc-com"
keywords = ["ipc", "shared-memory", "inter-process-communication"]
categories = ["os", "concurrency"]
rust-version = "1.85"

[dependencies]
libc = "0.2.189"

[profile.release]
opt-level = 3
lto = "fat"
strip = "symbols"
panic = "abort"

[lints.clippy]
mem_forget = "deny"
exit = "warn"
dbg_macro = "deny"
todo = "warn"
unimplemented = "warn"

large_stack_arrays = "warn"
large_futures = "warn"
needless_pass_by_value = "warn"
redundant_clone = "deny"
