[package]
name = "ipc-com"
version = "0.2.4"
edition = "2024"
description = "Linux interprocess communication using shared memory and futexes"
license = "Apache-2.0"
repository = "https://github.com/CosmicalBit/Ipc-com"
keywords = ["ipc", "shared-memory", "interprocess", "linux", "futex"]
categories = ["os", "concurrency", "memory-management"]
rust-version = "1.87"

[dependencies]
libc = "0.2.189"

[profile.release]
opt-level = 3
lto = "fat"
strip = "symbols"
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
lto = "fat"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
mem_forget = "deny"
exit = "warn"
dbg_macro = "deny"
trivially_copy_pass_by_ref = "warn"
large_types_passed_by_value = "warn"
cast_possible_truncation = "deny"
cast_possible_wrap = "warn"
cast_sign_loss = "warn"
cast_lossless="warn"

todo = "warn"
unimplemented = "warn"
needless_pass_by_ref_mut = "warn"

large_stack_arrays = "warn"
large_futures = "warn"
needless_pass_by_value = "warn"
redundant_clone = "deny"
